init add virt-install to qa_test_virtualization

diff --git a/tests/qa_test_virtualization/qa_test_virtualization/shared/standalone b/tests/qa_test_virtualization/qa_test_virtualization/shared/standalone
--- a/tests/qa_test_virtualization/qa_test_virtualization/shared/standalone
+++ b/tests/qa_test_virtualization/qa_test_virtualization/shared/standalone
@@ -47,14 +47,16 @@ TESTUSER_PASSWD="virt-pass-159"
 
 DEFAULT_IF="`route | grep ^default | awk {'print $NF'}`"
 
-BACKUP="`mktemp -d`"
+BACKUP="/tmp/virt_conf/"
+
+mkdir $BACKUP 2>/dev/null
 
 # add some file/dir to backup
 function backup
 {
 	#list for later removal during restore
-	echo -n "$1" >> "$BACKUP/LIST.$$"
-	echo -ne "\0" >> "$BACKUP/LIST.$$"
+	echo -n "$1" >> "$BACKUP/LIST"
+	echo -ne "\0" >> "$BACKUP/LIST"
 
 	dir="`dirname "$1"`"
 	if [ -e "$1" ] ; then 
@@ -71,8 +73,8 @@ function backup_copy
 
 function restore
 {
-	cat "$BACKUP/LIST.$$" | xargs -0 rm -rf
-	rm "$BACKUP/LIST.$$"
+	cat "$BACKUP/LIST" | xargs -0 rm -rf
+	rm "$BACKUP/LIST"
 
 	cp -a "$BACKUP"/* /
 	rm -fr "$BACKUP"
@@ -92,18 +94,14 @@ function test_cleanup
 
 
 #
-function _test_init
+function setup_services
 {
-	#check improper cleanup from last time
 	failed=0
+	#check improper cleanup from last time
 	if ifconfig $BR > /dev/null 2>&1 ; then
-		echo "Error: Cannot create bridge $BR, network interface with same name already exist." >&2
-		echo "       If it's a result of improper cleanup from last time, you can do:" >&2
-		echo "           ifconfig $BR down ; brctl delbr $BR" >&2
-		echo "       You should also check your resolv.conf. If it contains wrong dns (localhost) and"
-		echo "       it was originally generated by netconfig, you can fix it by following command:" >&2
-		echo "           netconfig -f update" >&2
-		failed=1
+		echo "Warning: Cannot create bridge $BR, network interface with same name already exist." >&2
+		echo "Skip setup service."
+		return
 	fi
 	if getent passwd $TESTUSER > /dev/null 2>&1 ; then
 		echo "Error: Cannot create user $TESTUSER, user with same name already exist." >&2
@@ -141,71 +139,6 @@ service tftp
 EOF
 
 	cp /usr/share/syslinux/pxelinux.0 /tftpboot
-
-	# If we are fully-virtualized, network, we need to download linux/initrd for pxe boot
-	# This must be in same location that vm-install.sh expect it!!!
-	if [ "$VIRT_TYPE" == "fv" ]
-	then
-		if [ "$INSTALL_METHOD" == "ftp" ] || [ "$INSTALL_METHOD" == "http" ] || [ "$INSTALL_METHOD" == "nfs" ] || [ "$INSTALL_METHOD" == "net" ]
-		then
-
-			pxe_os=OOPS
-			pxe_rl="$RELEASE"
-			pxe_sp="$SERVICE_PACK"
-			if [ "$ARCHITECTURE" == "32" ] || [ "$ARCHITECTURE" == "32p" ] ; then
-				arch="ix86"
-			elif [ "$ARCHITECTURE" == "64" ] ; then
-				arch="x86_64"
-			fi
-			if [ "$OPERATING_SYSTEM" == "sles" ] || [ "$OPERATING_SYSTEM" == "sled" ] || [ "$OPERATING_SYSTEM" == "oes" ] ; then
-				pxe_os="$OPERATING_SYSTEM"
-				os_type=suse
-			elif [ "$OPERATING_SYSTEM" == "os" ] ; then
-				pxe_os=opensuse
-				os_type=suse
-			elif [ "$OPERATING_SYSTEM" == "rhel" ]
-			then
-				pxe_os=rhel
-				os_type=rhel
-			fi
-
-			if [ "$pxe_os" == "OOPS" ] ; then
-				tmpError="PXE os --$pxe_os--, PXE RELEASE --$pxe_rl-- or PXE sp --$pxe_sp-- not set correctly"
-				echo "ERROR - $tmpError"
-				echo "ERROR - $tmpError" >&2
-				echo "    ***** INSTALL ERRORED *****"
-				popd > /dev/null; return 11
-			fi
-
-			# get initrd and kernel
-			sr=`/usr/share/qa/virtautolib/lib/get-source.sh source.$INSTALL_METHOD.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE`
-			if [ "$INSTALL_METHOD" == "nfs" -o "$INSTALL_METHOD" == "net" ] ; then
-				# nfs not supported, trying ftp or http
-				sr=`/usr/share/qa/virtautolib/lib/get-source.sh source.ftp.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE`
-				[ "$sr" == "" ] && sr=`/usr/share/qa/virtautolib/lib/get-source.sh source.http.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE`
-			fi
-			if [ "$sr" == "" ] ; then
-				tmpError="Unable to get ftp/http installation source for $OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE method: $INSTALL_METHOD."
-                                echo "ERROR - $tmpError"
-                                echo "ERROR - $tmpError" >&2
-                                echo "    ***** INSTALL SKIPPED *****"
-                                popd > /dev/null; return 22
-			fi
-			
-			mkdir -p /tftpboot/qa-virtauto/$pxe_os/$pxe_rl/$pxe_sp/$arch
-			cd /tftpboot/qa-virtauto/$pxe_os/$pxe_rl/$pxe_sp/$arch
-
-			if ! /usr/share/qa/virtautolib/lib/download_pxe_bootfiles.sh -ik -a $arch -s "$sr" -o $os_type ; then
-				tmpError="Unable to download initrd&kernel image from $sr."
-				echo "ERROR - $tmpError"
-				echo "ERROR - $tmpError" >&2
-				echo "    ***** INSTALL ERRORED *****"
-				popd > /dev/null; return 11
-			fi
-
-			cd - > /dev/null
-		fi
-	fi
 
 	# DHCP
 	backup /etc/sysconfig/dhcpd
@@ -339,10 +272,10 @@ EOF
 
 
 	# modify resolv.conf
-	cp /etc/resolv.conf /etc/resolv.conf.$$
-	sed -i 's/^\(search .*\)$/\1 testvirt.net/' /etc/resolv.conf.$$
-	grep -v '^nameserver ' /etc/resolv.conf.$$ > /etc/resolv.conf
-	rm /etc/resolv.conf.$$
+	cp /etc/resolv.conf /etc/resolv.conf
+	sed -i 's/^\(search .*\)$/\1 testvirt.net/' /etc/resolv.conf
+	grep -v '^nameserver ' /etc/resolv.conf > /etc/resolv.conf
+	rm /etc/resolv.conf
 	echo 'nameserver 127.0.0.1' >> /etc/resolv.conf
 
 	# Web server for autoinst profiles
@@ -367,7 +300,7 @@ EOF
 
 	# NAT - TODO, create more complete rules so it's not neccessary to disable firewall
 	rcSuSEfirewall2 stop
-	iptables-save > /tmp/iptables.$$
+	iptables-save > /tmp/iptables
 	iptables --table nat --append POSTROUTING --out-interface $DEFAULT_IF -j MASQUERADE
 	iptables --append FORWARD --in-interface $BR -j ACCEPT
 	echo 1 > /proc/sys/net/ipv4/ip_forward
@@ -397,6 +330,80 @@ EOF
 	test_init
 }
 
+function _test_init
+{
+	
+	#setup services
+	setup_services
+	
+	
+	#download the kernel and initrd for pxe install
+	
+	if [ "$VIRT_TYPE" == "fv" ]
+	then
+		if [ "$INSTALL_METHOD" == "ftp" ] || [ "$INSTALL_METHOD" == "http" ] || [ "$INSTALL_METHOD" == "nfs" ] || [ "$INSTALL_METHOD" == "net" ]
+		then
+	
+			pxe_os=OOPS
+			pxe_rl="$RELEASE"
+			pxe_sp="$SERVICE_PACK"
+			if [ "$ARCHITECTURE" == "32" ] || [ "$ARCHITECTURE" == "32p" ] ; then
+				arch="ix86"
+			elif [ "$ARCHITECTURE" == "64" ] ; then
+				arch="x86_64"
+			fi
+			if [ "$OPERATING_SYSTEM" == "sles" ] || [ "$OPERATING_SYSTEM" == "sled" ] || [ "$OPERATING_SYSTEM" == "oes" ] ; then
+				pxe_os="$OPERATING_SYSTEM"
+				os_type=suse
+			elif [ "$OPERATING_SYSTEM" == "os" ] ; then
+				pxe_os=opensuse
+				os_type=suse
+			elif [ "$OPERATING_SYSTEM" == "rhel" ]
+			then
+				pxe_os=rhel
+				os_type=rhel
+			fi
+	
+			if [ "$pxe_os" == "OOPS" ] ; then
+				tmpError="PXE os --$pxe_os--, PXE RELEASE --$pxe_rl-- or PXE sp --$pxe_sp-- not set correctly"
+				echo "ERROR - $tmpError"
+				echo "ERROR - $tmpError" >&2
+				echo "    ***** INSTALL ERRORED *****"
+				popd > /dev/null; return 11
+			fi
+	
+			# get initrd and kernel
+			sr=`/usr/share/qa/virtautolib/lib/get-source.sh source.$INSTALL_METHOD.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE`
+			if [ "$INSTALL_METHOD" == "nfs" -o "$INSTALL_METHOD" == "net" ] ; then
+				# nfs not supported, trying ftp or http
+				sr=`/usr/share/qa/virtautolib/lib/get-source.sh source.ftp.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE`
+				[ "$sr" == "" ] && sr=`/usr/share/qa/virtautolib/lib/get-source.sh source.http.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE`
+			fi
+			if [ "$sr" == "" ] ; then
+				tmpError="Unable to get ftp/http installation source for $OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE method: $INSTALL_METHOD."
+	                        echo "ERROR - $tmpError"
+	                        echo "ERROR - $tmpError" >&2
+	                        echo "    ***** INSTALL SKIPPED *****"
+	                        popd > /dev/null; return 22
+			fi
+			
+			mkdir -p /tftpboot/qa-virtauto/$pxe_os/$pxe_rl/$pxe_sp/$arch
+			cd /tftpboot/qa-virtauto/$pxe_os/$pxe_rl/$pxe_sp/$arch
+	
+			if ! /usr/share/qa/virtautolib/lib/download_pxe_bootfiles.sh -ik -a $arch -s "$sr" -o $os_type ; then
+				tmpError="Unable to download initrd&kernel image from $sr."
+				echo "ERROR - $tmpError"
+				echo "ERROR - $tmpError" >&2
+				echo "    ***** INSTALL ERRORED *****"
+				popd > /dev/null; return 11
+			fi
+	
+			cd - > /dev/null
+		fi
+	fi
+	}
+
+
 #
 function _test_cleanup
 {
@@ -408,25 +415,9 @@ function _test_cleanup
 		"$TEST_ROOT/loc/cleanup.$LOCATION" || res=$?
 	fi
 
-	rcxinetd stop
-	rcdhcpd stop
-	rcnamed stop
-	rcapache2 stop
-	
-	delUser $TESTUSER || res=1
-
-	#restore orig. files (that were backed up)
-	restore
-
-	cat /tmp/iptables.$$ | iptables-restore
-	rm /tmp/iptables.$$
-
-	ifconfig $BR down
-	brctl delbr $BR
-
-	#update resolv conf
-	grep -q 'generated by netconfig' /etc/resolv.conf && netconfig -f update
 	return $res
+
+
 }
 
 #run test itself
@@ -436,13 +427,13 @@ function run_test
         sf="$TEST_ROOT/loc/sources.$LOCATION"
 	[ -f "$sf" ] || sf=/usr/share/qa/virtautolib/data/settings.properties
 	if [ "$INSTALL_METHOD" == 'net' ] ; then
-		if ! /usr/share/qa/virtautolib/lib/get-source.sh source.ftp.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE > /dev/null2> /dev/null \
-			&& ! /usr/share/qa/virtautolib/lib/get-source.sh source.http.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE > /dev/null2> /dev/null ; then
+		if ! /usr/share/qa/virtautolib/lib/get-source.sh source.ftp.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE > /dev/null 2> /dev/null \
+			&& ! /usr/share/qa/virtautolib/lib/get-source.sh source.http.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE > /dev/null 2> /dev/null ; then
 			printSkipped "Source: source.$INSTALL_METHOD.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE not defined in $sf." >&2
 			exit $SKIPPED
 		fi
 	else
-		if ! /usr/share/qa/virtautolib/lib/get-source.sh source.$INSTALL_METHOD.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE > /dev/null2> /dev/null ; then
+		if ! /usr/share/qa/virtautolib/lib/get-source.sh source.$INSTALL_METHOD.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE > /dev/null 2> /dev/null ; then
 			printSkipped "Source: source.$INSTALL_METHOD.$OPERATING_SYSTEM-$RELEASE-$SERVICE_PACK-$ARCHITECTURE not defined in $sf." >&2
 			exit $SKIPPED
 		fi
